# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
coverage:
  status:
    patch:
      default:
        target: 80
    project:
      default: false
      utils:
        paths:
          - src/utils
        threshold: 0.5
      farajaland:
        paths:
          - src/farajaland
        threshold: 0.5

ignore:
  - 'src/farajaland/config'
  - 'src/farajaland/features/administrative/generated'
  - 'src/farajaland/features/administrative/scripts'
  - 'src/farajaland/features/administrative/source'
  - 'src/farajaland/features/employees'
  - 'src/farajaland/features/facilities/generated'
  - 'src/farajaland/features/facilities/scripts'
  - 'src/farajaland/features/facilities/source'
  - 'src/farajaland/features/languages/generated'
